# -*- coding: utf-8 -*-
"""flask_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0km6C9YD7zHXv9o_UYLrZThsMq7uHpx
"""

from flask import Flask, request, jsonify

app = Flask(__name__)

# Mock Recommendation Data
collab_recommendations = {
    1: ['B', 'C', 'D'],
    2: ['A', 'D', 'C'],
}
content_recommendations = {
    'A': ['B', 'C'],
    'B': ['A', 'C'],
}

@app.route('/recommend', methods=['GET'])
def recommend():
    user_id = request.args.get('user_id', type=int)
    item_id = request.args.get('item_id', type=str)

    # Collaborative Filtering Recommendations
    if user_id:
        recommendations = collab_recommendations.get(user_id, [])
        return jsonify({"user_id": user_id, "recommendations": recommendations})

    # Content-Based Recommendations
    elif item_id:
        recommendations = content_recommendations.get(item_id, [])
        return jsonify({"item_id": item_id, "recommendations": recommendations})

    return jsonify({"error": "Provide user_id or item_id"}), 400

if __name__ == "__main__":
    app.run(debug=True)